# Generated by Django 5.1.3 on 2024-12-04 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ("author",)},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ("-pub_date",)},
        ),
        migrations.AlterModelOptions(
            name="profile",
            options={"ordering": ("last_name",)},
        ),
    ]
