# Generated by Django 5.1.3 on 2024-12-12 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
